### ISSUE TITLE
Prometheus Proxy through Nginx reverse proxy 

### ISSUE THREAD

**Issue by vincedom** [pambrose/prometheus-proxy#81] opened 2022-11-07 08:37 UTC
Hi

I have exactly the same issue than https://github.com/pambrose/prometheus-proxy/issues/29 with the last release v1.14.1. I create a minimalist example to reproduce the problem there (https://github.com/vincedom/prom-proxy-nginx/tree/main).

I also investigate it more deeply. The problem seems that when using nginx we go through io.prometheus.proxy.ProxyServerTransportFilter->transportReady and io.prometheus.proxy.ProxyServerTransportFilter->transportTerminated for each api call.
So when the agent calls connectAgent the agentContext is created at the begin of the call and remove at the end, so when it calls registerAgent there was an error since agentContext is missing.
I make my example "works" by removing the call to proxy.removeAgentContext in transportTerminated, but of course this is not a true fix since it's generated memory leaks, however it's demonstrated that this is the right problem.
I can't go further since I don't known Kotlin neither gRPC.

According to me, your project aims to use Prometheus through firewall or more generally in non easily accessible installations so it would make sense, to have a robust connection that can go through proxy and reverse proxy.

Thanks by advance, and thanks for your great job.
Regards

Vincent

**Comment by vincedom** [comment] 2022-11-08 09:20
Hi Paul

Indeed, #29 want to support SSL. But for that #29 does not use the builtin SSL of prometheus-proxy, but do it via nginx having plain gRPC between Nginx and prometheus-proxy. 
The last problem of #29 is not and SSL problem but a proxy problem. I can reproduce the problem without SSL but only with nginx proxy. 

This is our architecture.  
![Architecture-prom-proxy drawio](https://user-images.githubusercontent.com/38553191/200524640-b0b3de40-1d43-45fc-ad47-728897362926.png)

Thanks 

Vincent

**Comment by pambrose** [comment] 2022-11-08 16:08
Okay, so your issue is your agent is not able to reach the Prometheus proxy when going through Nginx. Is that correct?

**Comment by vincedom** [comment] 2022-11-08 16:25
The proxy agent is able to reach the prometheus-proxy, but when the prometheus-agent try to register (after connected) the prometheus-proxy did not find the agentcontext and send an "invalid agent id" message.

**Comment by pambrose** [comment] 2022-11-08 16:58
Great. I am busy the rest of this week, but I will work on this over the weekend. I know gRPC works with Nginx, so I suspect it is just a config issue.

**Comment by collective-thinking** [comment] 2022-11-23 10:44
Hi Paul 
Have you had time to look at this issue ? 

Regards

**Comment by vincedom** [comment] 2022-11-23 10:45
Hi Paul 

Have you had time to look at this issue ? 

Regards

**Comment by pambrose** [comment] 2022-11-24 08:45
Hi Vincent,

Sorry, I have not forgotten about this. Something came up, but I will get to it between now and Monday.

**Comment by pambrose** [comment] 2022-11-26 08:08
Hi Vincent,

I have recreated your setup and I see the issue. When nginx is involved, a disconnect message is being propagated back to the proxy (within the gRPC framework) after a gRPC call is made. When a disconnect is triggered, then the resources associated with that connection are cleaned up on the proxy. In this case, the context data for the agent is being prematurely removed as a result of the errant disconnect message. I am not sure why this happening, but I am looking into it.

**Comment by pambrose** [comment] 2022-11-26 21:43
I use an instance of io.grpc.ServerTransportFilter (io.prometheus.proxy.ProxyServerTransportFilter) to listen for server transport life-cycle events. Specifically, I listen for when the transport is ready and terminated. In those callbacks, I perform housekeeping on agent context values, which enables session mgmt. ServerTransportFilter is an experimental API (https://github.com/grpc/grpc-java/issues/2132). 

The problem is, nginx is yielding different server transport event behavior. Specifically, every single gRPC is invoking the transportReady() and transportTerminated() callbacks. So the context mgmt is screwed up. Without nginx, the transportReady() and transportTerminated() callbacks are invoked once per client session.

I do not think the nginx gRPC support includes support for ServerTransportFilter because it is experimental. ejona86's comment talks about it being problematic with load balancers: https://github.com/grpc/grpc-java/issues/2132#issuecomment-359611387 

So I am afraid the proxy is not going to work with nginx. I am sorry about that. I am also sorry for taking so long to address this issue.

**Comment by pambrose** [comment] 2022-11-28 08:43
Hi Vincent,

I looked at the code some more. I think we can make the ServerTransportFilter session mgmt optional. The only cost would be agent contexts would have to get timed out after no activity when agents disconnect prematurely, which would be fine in most cases. That is the existing backup behavior already in place. 

Give me a couple of days to get you something to try.

**Comment by pambrose** [comment] 2022-11-29 07:53
Hi Vincent,

Can you please try the 1.15.0-b1 release? Release notes are [here](https://github.com/pambrose/prometheus-proxy#nginx-support).

The prometheus_proxy code is working properly, but nginx is closing the connection every 60s, which causes the agent to reconnect. I googled around and found that I am not the first to have [ this issue](https://stackoverflow.com/questions/67430437/grpc-send-timeout-doesnt-work-nginx-closes-grpc-streams-unexpectedly). Let's see how it works for you and then we can figure out how to resolve the nginx issue.

**Comment by Altiire** [comment] 2022-11-29 14:58
![image](https://user-images.githubusercontent.com/1278544/204563033-ccabea89-8f18-4a8e-934e-050e69a1fe6a.png)

![image](https://user-images.githubusercontent.com/1278544/204563099-caa515a1-9b08-465a-a4ad-d7557bff06b7.png)

![image](https://user-images.githubusercontent.com/1278544/204563194-ff593433-0624-4202-8bab-2e20535963a1.png)

I'm using Apache2 but it shouldn't be a problem here

**Comment by pambrose** [comment] 2022-11-29 17:50
Can you check the agent's log and confirm that you see "transportFilterDisabled: true" when it reports property values during initialization? The log message error suggests it is not getting set to true.

**Comment by vincedom** [comment] 2022-11-30 15:51
Hi Paul

I have check on my side and indeed the TRANSPORT_FILTER_DISABLED env variable does not work on the agent, but the variable "transportFilterDisabled: true"  in the config file does. It works for me using nginx now ! 
By the way, behond the nginx problem I think it's a great feature to not rely on transport layer for you solution. From my point of view your solutions is for connecting "far away" locations (so bypass proxy, firewall, and more). That's why using transport layer, for me, was an error. 

Regards

Vincent

**Comment by pambrose** [comment] 2022-12-01 07:55
Hi Vincent,

I checked the TRANSPORT_FILTER_DISABLED env variable, and it is working for me. Can you double-check the way you are setting it?

I am glad to hear it is working for you!

When you suggest not relying on the "transport layer" are you referring to the recent TRANSPORT_FILTER_DISABLED change or gRPC in general?

Paul

**Comment by pambrose** [comment] 2022-12-15 05:52
Hi @vincedom. Are you good with this issue?

**Closed** 2023-07-19 20:45 UTC
